### ISSUE TITLE
Create new recipient

### ISSUE THREAD

**Issue by cajkovski** [onlinecity/wp-gatewayapi#26]
HI, I am having issue with adding a new recipient.  I can not choose a country code in drop-downs menu.

 Please see attached picture. I tested it on two different WP sites .

Best regards, Amer
![wp1](https://cloud.githubusercontent.com/assets/25405971/22488696/d17ae4f4-e813-11e6-8e29-4c83d707237b.jpg)

**Comment by bitnissen** [comment]
Dear Amer,

It works flawlessly in the test-setups I have. Could you perhaps give some more details about your setup? Browser and browser version (in doubt, [try this tool](https://www.whatismybrowser.com))? PHP-version? WordPress-version?

If you have Google Chrome, then if you could open up there and try to open the Developer Console (right-click somewhere on the page and click "Inspect"). Then change to the tab "Network" and filter "XHR"-requests. Finally reload the page and in the list of resources, there should be a `countries.min.js`.

Here's how it looks with me:
<img src="http://d.pr/i/4NzH/2tMGh7on.png">

Can you confirm the issue in Google Chrome? What output do you get in the network-tab?

Kind regards,
Bitnissen

**Comment by cajkovski** [comment]
HI, thanks for yours support

I am using shared hosting att one.com, currently it is php 5.6 but I am on
way at update to php 7.0 and see if it is any changes.

I tested it with Firefox, Chrome, Opera, Microsoft Edge and Vivaldi) I can
see all countries on tab preview with all browsers
Today I will test it on new-fresh  WP page.

Best regards, Amer

**Comment by bitnissen** [comment]
Dear Amer,

Your welcome. Just to understand your last message, does it work or does it not work in the tested browsers?

If possible, try do the inspection of the network connection, as suggested. The list of countries is downloaded by the browser via AJAX, so my theory is that for some reason, the browser does not download this list. Maybe because some other plugin interferes, maybe there's a browser-specific bug, maybe hosting related... It may also download the list, but for some reason cannot parse it in your setup. In any case, I need a bit more data, to try and reproduce the issue.

Kind regards,
Bitnissen

**Comment by cajkovski** [comment]
No it does not work, I meant to say I see it under network connection (Developer Console).

I will try it on own VPS  and new fresh WP.



![wp4](https://cloud.githubusercontent.com/assets/25405971/22501581/b1c6d95a-e869-11e6-9628-874c696f17bb.jpg)

**Comment by bitnissen** [comment]
Hi Amer,

Ok, are there any Javascript-errors? To find out, check out the "Console"-tab and reload.

Could you perhaps send a list of plugins activated on your install? If you could, try and disable all other plugins and see if the issue still persists. If it starts working, then try enabling the plugins one-by-one and we should find out if there's a plugin causing the issues.

Kind regards,
Morten

**Comment by cajkovski** [comment]
I disabled all plugins except GatewayAPI and I got same result.

As far as I can see there is no  Javascript-errors

just this in log:

JQMIGRATE: Migrate is installed, version 1.4.1
Navigated to http://s-d-o.org/wp-admin/edit.php?post_type=gwapi-recipient
load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,plupload&ver=4.7.2:9
JQMIGRATE: Migrate is installed, version 1.4.1
Navigated to http://s-d-o.org/wp-admin/post-new.php?post_type=gwapi-sms
load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,plupload&ver=4.7.2:9
JQMIGRATE: Migrate is installed, version 1.4.1
Navigated to
http://s-d-o.org/wp-admin/edit-tags.php?taxonomy=gwapi-recipient-groups&post_type=gwapi-recipient
load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,plupload&ver=4.7.2:9
JQMIGRATE: Migrate is installed, version 1.4.1

**Comment by bitnissen** [comment]
Hi Amer,

This is strange... I tried the same on my computer, setting the PHP-version to 5.6 etc., disabled all plugins, but everything still works.

Do you have a test-site or something, where you could create a user for me? Then I'll try and log in and see if I can figure out what goes wrong. Editor-role should be sufficient.

You may invite ms@onlinecity.dk.

If not possible, then that's totally ok, but it would make debugging this issue easier.

Kind regards,
Bitnissen

**Comment by cajkovski** [comment]
it's done,  you have access now

thanks

**Comment by bitnissen** [comment]
Dear Amer,

Thanks! I also found the issue :-)

It appears that one.com does not set the correct headers on JSON-files, but instead resolves them as the mime type `text/plain`. Therefore jQuery does not extract the JSON from the AJAX-request.

I will apply a workaround for this in a moment. Stay tuned :-)

**Comment by bitnissen** [comment]
P.S. You are welcome to delete my user from your installation. I will not need it anymore.

**Comment by bitnissen** [comment]
Dear Amer.

Please try the latest release - it should be possible to auto-update within 30 minutes or so from the backend, or you can get it without any waiting from here:

https://github.com/onlinecity/wp-gatewayapi/archive/1.4.1.zip

**Comment by cajkovski** [comment]
I  will have to wait a little bit,  currently I don't have access to my
workstation,  I am writing from mobile.

**Comment by cajkovski** [comment]
I can confirm now it works after latest update. 

huge thanks for all yours work 

Best regards, Amer

**Comment by bitnissen** [comment]
Your welcome, thanks for the feedback :-)
