### ISSUE TITLE
No whitelist for links configured.

### ISSUE THREAD

**Issue by simplenotezy** [onlinecity/wp-gatewayapi#30]
Hi there,

I can't send 2FA sms'es due to the error:

`The SMS could not be sent, due to the SMS-service rejecting to send the message.`

Technical reason:
- No whitelist for links configured.

Code 0x0312
UUID: 944f3494-4655-42b8-8d70-6b22fee12fb7

**Comment by Dolriis** [comment]
Hi there @simplenotezy, this has been adrressed in our newest release of the plugin, and should no longer be an issue.
