### ISSUE TITLE
Add option or filter for setting default country code

### ISSUE THREAD

**Issue by thomasmb** [onlinecity/wp-gatewayapi#32]
When 2FA is enabled, the user will be asked to add a phone number on first login. This country code field defaults to +45. It would be great if this was an option.

Adding a crude example to show my point, by adding attempting to get the option at and apply a filter at line 17 in tpl/wp-login-add-phone.php – with a default of 45.

```
<select name="mcc" id="gwapi_mcc" data-gwapi-mobile-cc data-default-cc="<?php echo apply_filters('gwapi_default_country_code', get_option( 'gwapi_default_country_code, 45 ) ); ?>" style="width: 100%"
```

I would suggest that this would call a function instead though, to keep the code clean.

**Comment by bitnissen** [comment]
Hi Thomas! Good idea, I have passed it on to our project manager. I don't really see any issues with your solution, besides that we should maybe add a UI to setup such a default as well, so the default could be changed in the plugins settings, and also overridden by a filter.

**Comment by thomasmb** [comment]
Any update on this?

**Comment by bitnissen** [comment]
@thomasmb Hi there :) It is possible now, the latest release (just released!) has received this exact feature.
![CleanShot 2021-06-14 at 16 08 39](https://user-images.githubusercontent.com/629954/121905892-e046f800-cd2a-11eb-90a6-8584f5b54f7e.png)
